### ISSUE TITLE
Does not respond to the minPoints parameter

### ISSUE THREAD

**Issue by valera7979** [mraad/dbscan-spark#2]
Hi, 

Thanks a lot for great job. This code really works. But i found when tested on my data that it does not respond to the minPoints parameter - the minimum number of points when we consider that this is a cluster. May even put one point in a separate cluster (gives the number, but should give 0 if it is noise).

**Comment by mraad** [comment]
Glad you like the code - as to minPoints, the property is 'dbscan.min.points'
And one more clarification, min points is _not_ the number of points to form a cluster, it is the min number of neighbors of a point to join an existing cluster. This small nuance trips people.
Please keep the feedback coming, Thanks

**Comment by valera7979** [comment]
Thanks. It seems to me, as a result this should lead to the cluster size that can not be less than 'dbscan.min.points'. Besides that in comments: 

 /* @param minPoints the minimum number of points in a neighborhood to start forming a cluster.

Whatever it is, I get a certain number of clusters with a small number of points (2-3 or even 1) in each, which are essentially noises. They should also be noted as belonging to 0.

**Comment by mraad** [comment]
I see what u r saying...let me investigate more.

**Comment by valera7979** [comment]
I just understood the meaning of the minPts. If the neighbor's point is less than minPts, then it will not be included in the cluster. If for example there is a point around which there are 5 points and minPts=5, then it can be included in the cluster, and the remaining 5 will not be in the cluster. There may be a situation where there is only one point in the cluster.

For example: let minPts = 4 and epsilon = 2 (distance between points = 1)
  o  o  **o**  o  o   

In this case, the cluster will consist of a single point

**Comment by randallwhitman** [comment]
> If the neighbor's point is less than minPts, then it will not be included in the cluster.

That's true of DBSCAN* [Star], which includes Core points only in a cluster; but original DBSCAN includes the Border points in the cluster.
